# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_server_status_status_get(self) -> None:
        """Test case for get_server_status_status_get

        Get Server Status
        """
        pass

    def test_get_shutter_list_get(self) -> None:
        """Test case for get_shutter_list_get

        Get Shutter List
        """
        pass

    def test_get_shutter_state_shutter_name_get(self) -> None:
        """Test case for get_shutter_state_shutter_name_get

        Get Shutter State
        """
        pass

    def test_login_for_access_token_token_post(self) -> None:
        """Test case for login_for_access_token_token_post

        Login For Access Token
        """
        pass

    def test_set_shutter_state_shutter_name_post(self) -> None:
        """Test case for set_shutter_state_shutter_name_post

        Set Shutter State
        """
        pass


if __name__ == '__main__':
    unittest.main()
