/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIShutterAction.h
 *
 * 
 */

#ifndef OAIShutterAction_H
#define OAIShutterAction_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIShutterAction : public OAIEnum {
public:
    OAIShutterAction();
    OAIShutterAction(QString json);
    ~OAIShutterAction() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIShutterAction {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        ON, 
        OFF, 
        SWITCH
    };
    OAIShutterAction::eOAIShutterAction getValue() const;
    void setValue(const OAIShutterAction::eOAIShutterAction& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIShutterAction m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIShutterAction)

#endif // OAIShutterAction_H
