/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIShutterStateReport.h
 *
 * 
 */

#ifndef OAIShutterStateReport_H
#define OAIShutterStateReport_H

#include <QJsonObject>

#include "OAIShutterState.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIShutterStateReport : public OAIObject {
public:
    OAIShutterStateReport();
    OAIShutterStateReport(QString json);
    ~OAIShutterStateReport() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getShutterName() const;
    void setShutterName(const QString &shutter_name);
    bool is_shutter_name_Set() const;
    bool is_shutter_name_Valid() const;

    OAIShutterState getState() const;
    void setState(const OAIShutterState &state);
    bool is_state_Set() const;
    bool is_state_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_shutter_name;
    bool m_shutter_name_isSet;
    bool m_shutter_name_isValid;

    OAIShutterState m_state;
    bool m_state_isSet;
    bool m_state_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIShutterStateReport)

#endif // OAIShutterStateReport_H
