/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIShutterAction.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIShutterAction::OAIShutterAction(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIShutterAction::OAIShutterAction() {
    this->initializeModel();
}

OAIShutterAction::~OAIShutterAction() {}

void OAIShutterAction::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIShutterAction::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIShutterAction::fromJson(QString jsonString) {
    
    if ( jsonString.compare("ON", Qt::CaseInsensitive) == 0) {
        m_value = eOAIShutterAction::ON;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("OFF", Qt::CaseInsensitive) == 0) {
        m_value = eOAIShutterAction::OFF;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("SWITCH", Qt::CaseInsensitive) == 0) {
        m_value = eOAIShutterAction::SWITCH;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIShutterAction::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIShutterAction::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIShutterAction::ON:
            val = "ON";
            break;
        case eOAIShutterAction::OFF:
            val = "OFF";
            break;
        case eOAIShutterAction::SWITCH:
            val = "SWITCH";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIShutterAction::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIShutterAction::eOAIShutterAction OAIShutterAction::getValue() const {
    return m_value;
}

void OAIShutterAction::setValue(const OAIShutterAction::eOAIShutterAction& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIShutterAction::isSet() const {
    
    return m_value_isSet;
}

bool OAIShutterAction::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
