/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIShutterChannelList.h
 *
 * 
 */

#ifndef OAIShutterChannelList_H
#define OAIShutterChannelList_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIShutterChannelList : public OAIObject {
public:
    OAIShutterChannelList();
    OAIShutterChannelList(QString json);
    ~OAIShutterChannelList() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QString> getShutterList() const;
    void setShutterList(const QList<QString> &shutter_list);
    bool is_shutter_list_Set() const;
    bool is_shutter_list_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<QString> m_shutter_list;
    bool m_shutter_list_isSet;
    bool m_shutter_list_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIShutterChannelList)

#endif // OAIShutterChannelList_H
