/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIShutterState.h
 *
 * 
 */

#ifndef OAIShutterState_H
#define OAIShutterState_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIShutterState : public OAIEnum {
public:
    OAIShutterState();
    OAIShutterState(QString json);
    ~OAIShutterState() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIShutterState {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        OFF, 
        ON
    };
    OAIShutterState::eOAIShutterState getValue() const;
    void setValue(const OAIShutterState::eOAIShutterState& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIShutterState m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIShutterState)

#endif // OAIShutterState_H
