/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIShutterState.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIShutterState::OAIShutterState(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIShutterState::OAIShutterState() {
    this->initializeModel();
}

OAIShutterState::~OAIShutterState() {}

void OAIShutterState::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIShutterState::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIShutterState::fromJson(QString jsonString) {
    
    if ( jsonString.compare("OFF", Qt::CaseInsensitive) == 0) {
        m_value = eOAIShutterState::OFF;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ON", Qt::CaseInsensitive) == 0) {
        m_value = eOAIShutterState::ON;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIShutterState::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIShutterState::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIShutterState::OFF:
            val = "OFF";
            break;
        case eOAIShutterState::ON:
            val = "ON";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIShutterState::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIShutterState::eOAIShutterState OAIShutterState::getValue() const {
    return m_value;
}

void OAIShutterState::setValue(const OAIShutterState::eOAIShutterState& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIShutterState::isSet() const {
    
    return m_value_isSet;
}

bool OAIShutterState::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
