/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIShutterStateReport.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIShutterStateReport::OAIShutterStateReport(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIShutterStateReport::OAIShutterStateReport() {
    this->initializeModel();
}

OAIShutterStateReport::~OAIShutterStateReport() {}

void OAIShutterStateReport::initializeModel() {

    m_shutter_name_isSet = false;
    m_shutter_name_isValid = false;

    m_state_isSet = false;
    m_state_isValid = false;
}

void OAIShutterStateReport::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIShutterStateReport::fromJsonObject(QJsonObject json) {

    m_shutter_name_isValid = ::OpenAPI::fromJsonValue(m_shutter_name, json[QString("shutter_name")]);
    m_shutter_name_isSet = !json[QString("shutter_name")].isNull() && m_shutter_name_isValid;

    m_state_isValid = ::OpenAPI::fromJsonValue(m_state, json[QString("state")]);
    m_state_isSet = !json[QString("state")].isNull() && m_state_isValid;
}

QString OAIShutterStateReport::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIShutterStateReport::asJsonObject() const {
    QJsonObject obj;
    if (m_shutter_name_isSet) {
        obj.insert(QString("shutter_name"), ::OpenAPI::toJsonValue(m_shutter_name));
    }
    if (m_state.isSet()) {
        obj.insert(QString("state"), ::OpenAPI::toJsonValue(m_state));
    }
    return obj;
}

QString OAIShutterStateReport::getShutterName() const {
    return m_shutter_name;
}
void OAIShutterStateReport::setShutterName(const QString &shutter_name) {
    m_shutter_name = shutter_name;
    m_shutter_name_isSet = true;
}

bool OAIShutterStateReport::is_shutter_name_Set() const{
    return m_shutter_name_isSet;
}

bool OAIShutterStateReport::is_shutter_name_Valid() const{
    return m_shutter_name_isValid;
}

OAIShutterState OAIShutterStateReport::getState() const {
    return m_state;
}
void OAIShutterStateReport::setState(const OAIShutterState &state) {
    m_state = state;
    m_state_isSet = true;
}

bool OAIShutterStateReport::is_state_Set() const{
    return m_state_isSet;
}

bool OAIShutterStateReport::is_state_Valid() const{
    return m_state_isValid;
}

bool OAIShutterStateReport::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_shutter_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_state.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIShutterStateReport::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_shutter_name_isValid && m_state_isValid && true;
}

} // namespace OpenAPI
