/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIShutterChannelOperation.h
 *
 * 
 */

#ifndef OAIShutterChannelOperation_H
#define OAIShutterChannelOperation_H

#include <QJsonObject>

#include "OAIShutterAction.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIShutterChannelOperation : public OAIObject {
public:
    OAIShutterChannelOperation();
    OAIShutterChannelOperation(QString json);
    ~OAIShutterChannelOperation() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIShutterAction getAction() const;
    void setAction(const OAIShutterAction &action);
    bool is_action_Set() const;
    bool is_action_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIShutterAction m_action;
    bool m_action_isSet;
    bool m_action_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIShutterChannelOperation)

#endif // OAIShutterChannelOperation_H
